# permissions for end users to edit githubrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrunners-editor-role
rules:
- apiGroups:
  - operators.ikea.com
  resources:
  - githubrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.ikea.com
  resources:
  - githubrunners/status
  verbs:
  - get
