# permissions for end users to view githubrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrunners-viewer-role
rules:
- apiGroups:
  - operators.ikea.com
  resources:
  - githubrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.ikea.com
  resources:
  - githubrunners/status
  verbs:
  - get
