apiVersion: operators.ikea.com/v1alpha1
kind: GitHubRunners
metadata:
  name: githubrunners-sample
spec:
  affinity: {}
  annotations: {}
  appIdSecretKey: github-app-id
  appInstallIdSecretKey: github-install-id
  appName: actions-runner
  appPemSecretKey: github-pem
  appSecretName: github-app
  clusterPKI: false
  cpuLimit: 250m
  cpuRequest: 100m
  ephemeral: false
  githubAppId: ""
  githubAppInstallId: ""
  githubAppPem: ""
  githubDomain: ""
  githubOwner: <GitHubOrg>
  githubPat: ""
  githubRepository: ""
  imagePullSecrets: {}
  mavenconfig:
    enabled: true
    settingsFile: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
        <servers>
            <server>
              <username>username</username>
              <password>password</password>
              <id>central</id>
            </server>
            <server>
              <username>username</username>
              <password>password</password>
              <id>snapshots</id>
            </server>
        </servers>
        <profiles>
            <profile>
              <repositories>
                  <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>libs-release</name>
                    <url>http://repo1.maven.org/maven2/</url>
                  </repository>
                  <repository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>libs-snapshot</name>
                    <url>http://repo1.maven.org/maven2/</url>
                  </repository>
              </repositories>
              <pluginRepositories>
                  <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>plugins-release</name>
                    <url>http://repo1.maven.org/maven2/</url>
                  </pluginRepository>
                  <pluginRepository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>plugins-snapshot</name>
                    <url>http://repo1.maven.org/maven2/</url>
                  </pluginRepository>
              </pluginRepositories>
              <id>artifactory</id>
            </profile>
        </profiles>
        <activeProfiles>
            <activeProfile>artifactory</activeProfile>
        </activeProfiles>
        <proxies>
            <proxy>
              <id>My Proxy</id>
              <active>true</active>
              <protocol>http</protocol>
              <host>proxy.company.com</host>
              <port>8080</port>
              <username>dummy</username>
              <password>password</password>
              <nonProxyHosts>www.google.com|*.example.com</nonProxyHosts>
            </proxy>
        </proxies>
      </settings>
  memoryLimit: 1Gi
  memoryRequest: 512Mi
  nodeSelector: {}
  replicas: 1
  runnerEnv: null
  runnerGroup: ""
  runnerImage: quay.io/redhat-github-actions/runner
  runnerLabels: []
  runnerTag: v1
  secretKey: github-pat
  secretName: github-pat
  serviceAccountName: default
  
  
